[tool.poetry]
name = "benn"
version = "0.1.0"
description = ""
authors = ["Tan Chien Hao <tanchienhao@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "=3.6.7"
face-recognition = "^1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
